name: Publish to Marketplace

on:
  workflow_dispatch:
    # inputs:
    #   releaseURL:
    #     description: 'The exact VSIX download URL you want to publish'
    #     required: true

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with: 
          node-version: 12

      - id: update_version
        run: |
          $version=node -p "require('./package.json').version"
          $version=$version+"-${{github.sha}}"
          echo "::set-output name=VERSION::$version"
        shell: pwsh

      - run: npm install
      - run: npm run compile
      - run: python ./configurations/pack.py

      # - id: create_release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.CICD_TOKEN }}
      #   with:
      #     tag_name: v${{ steps.update_version.outputs.VERSION }}
      #     release_name: Release v${{ steps.update_version.outputs.VERSION }}
      #     body: Marketplace Release generated by from GitHub Action
      #     draft: false
      #     prerelease: false

      # - name: Upload vsix as release asset
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.CICD_TOKEN }}
      #   with:
      #     upload_url: ${{ steps.create_release.outputs.upload_url }}
      #     asset_path: ./agilebim.fabcod.vsix
      #     asset_name: agilebim.fabcod.vsix
      #     asset_content_type: application/zip
      
      
      - name: Publish to Visual Studio Marketplace
        uses: HaaLeo/publish-vscode-extension@v0
        with:
          pat: ${{ secrets.FABCODEXT_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com
          extensionFile: ./agilebim.fabcod.vsix
          packagePath: ''
